apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: animal-ingress
  annotations:
    # type of authentication
    nginx.ingress.kubernetes.io/auth-type: basic
    nginx.ingress.kubernetes.io/auth-secret: basic-auth
    nginx.ingress.kubernetes.io/auth-realm: 'Authentication Required - auth'
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /moose(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: moose-svc
            port:
              number: 80
      - path: /bear(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: bear-svc
            port:
              number: 80              
